collections:
  - name: community.mysql
    version: ">=3.0"
  - name: community.postgresql
    version: ">=3.4"
  - name: community.general
    version: ">=8.0"
  - name: community.hashi_vault
    version: ">=6.2"
