{{-- main Orchestrator --}}
@include('booking-adoption.main.head')
@include('booking-adoption.main.connectivity-page-header')
@include('booking-adoption.main.stats-search')
@include('booking-adoption.main.bookings-table')
@include('booking-adoption.main.payment-modal')
@include('booking-adoption.main.loading-adoption-modal')
@include('booking-adoption.main.scripts-data')
@include('booking-adoption.main.scripts-adoption-modal')
@include('booking-adoption.main.scripts-close')
